---
version: '3'

services: 
  db:
    image: mysql:5
    hostname: dbhost
    restart: always
    networks:
      - appnetwork
    ports:
      - "3306:3306"
    volumes: 
      - dbdata: "/var/lib/mysql"
    environment: 
      MYSQL_USER: bduser
      MYSQL_PASSWORD: BDPassWord123
      MYSQL_DATABASE: appbd
      MYSQL_ROOT_PASSWORD: BDPassWord123    

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always  
    hostname: apphost  
    networks:
      - appnetwork
    ports:
      - "8080:8080"
    
volumes: 
  dbdata:
networks: 
  appnetwork: